apiVersion: v1
kind: Service
metadata:
  name: dynamicinstrumentation-service
spec:
  type: Loadbalancer
  selector:
    app: dynamicinstrumentation
  ports:
    - name: "http"
      protocol: "TCP"
      port: 8090
      targetPort: 80
