apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "dynamicinstrumentation"
  labels:
    app: "dynamicinstrumentation"
    tags.datadoghq.com/env: "prod"
    tags.datadoghq.com/service: "dynamicinstrumentation"
    tags.datadoghq.com/version: "3.1030"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "dynamicinstrumentation"
      tags.datadoghq.com/env: "prod"
      tags.datadoghq.com/service: "dynamicinstrumentation"
      tags.datadoghq.com/version: "3.1030"
  template:
    metadata:
      labels:
        app: "dynamicinstrumentation"
        tags.datadoghq.com/env: "prod"
        tags.datadoghq.com/service: "dynamicinstrumentation"
        tags.datadoghq.com/version: "3.1030"
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/dotnet-lib.version: "v2.40.0"
    spec:
      containers:
        - name: "dynamicinstrumentation"
          image: "scotcurry4/dynamicinstrumentation:3.1030"
          ports:
            - containerPort: 80
          env:
            - name: DD_LOGS_INJECTION