apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "dynamicinstrumentation"
  labels:
    app: "dynamicinstrumentation"
    tags.datadoghq.com/env: "prod"
    tags.datadoghq.com/service: "dynamicinstrumentation"
    tags.datadoghq.com/version: "<DATADOG_VERSION>"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "dynamicinstrumentation"
      tags.datadoghq.com/env: "prod"
      tags.datadoghq.com/service: "dynamicinstrumentation"
      tags.datadoghq.com/version: "<DATADOG_VERSION>"
  template:
    metadata:
      labels:
        app: "dynamicinstrumentation"
        tags.datadoghq.com/env: "prod"
        tags.datadoghq.com/service: "dynamicinstrumentation"
        tags.datadoghq.com/version: "<DATADOG_VERSION>"
        tags.datadoghq.com/git.commit.sha: "<GIT_SHA>"
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/dotnet-lib.version: "v2.40.0"
    spec:
      containers:
        - name: "dynamicinstrumentation"
          image: "scotcurry4/dynamicinstrumentation:<DATADOG_VERSION>"
          ports:
            - containerPort: 80
          env:
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: DD_API_KEY
              value: "<DD_API_KEY>"
            - name: DD_APP_KEY
              value: "<DD_APP_KEY>"
            - name: DD_DYNAMIC_INSTRUMENTATION_ENABLED
              value: "true"
            - name: DD_GIT_COMMIT_SHA
              value: "<GIT_SHA>"
            