name: dynamicInstrumentation Build
on: [push]
jobs:
  build-dynamicInstrumenation:
    runs-on: ubuntu-latest
    steps:
      - name: Get-Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x
      
      - name: Restore the application
        run: dotnet restore
  
      - name: Dotnet Build
        run: dotnet build --configuration Release
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_AUTH_TOKEN }}
  
      - name: Docker Build and Push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:DynamicInstrumentation"
          platforms: linux/amd64,linux/arm64/v8
          push: true
          # Don't forget to set the IMAGE_NAME environment variable.
          tags: scotcurry4/curryware-front-end:${{ github.run_number}}
          labels: |
            org.opencontainers.image.source=github.com/scotcurry/DynamicInstrumentation
            org.opencontainers.image.revision=${{ github.sha }}
            tags.datadoghq.com/env=prod
            tags.datadoghq.com/version=${{ github.run_number }}
            tags.datadoghq.com/service=dynamicinstrumentation